name: Release workflow

on:
  release:
    types:
      - "published"

jobs:
  update-version:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version_file: ["api/Ballerina.toml", "cleint/Ballerina.toml"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set output
        id: vars
        # See: https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
        run: echo ::set-output name=tag::${GITHUB_REF#refs/v*/}
      - name: Update versions in package files
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: ${{ matrix.version_file }}
          key: "package.version"
          value: ${{ steps.vars.outputs.tag }}
  update-staging-db:
    name: Update Azure staging database
    needs: update-version
    runs-on: ubuntu-22.04
    environment: Staging
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update Azure staging database
        run: |
          ls
          pwd
          cat ./db/schema/*.sql | mysql --host=$HOST --port=$PORT --user=$USER --password=$PASSWORD
        env:
          HOST: ${{ secrets.DB_HOST }}
          PORT: ${{ secrets.DB_PORT }}
          USER: ${{ secrets.DB_USER }}
          PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE: ${{ secrets.DB_DATABASE }}
  push-api-client:
    name: Publish GraphQL API Client
    needs: update-staging-db
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build distribution archive of client package
        uses: ballerina-platform/ballerina-action@394eb82cc07e020948fee8d1474143ae393147f4
        with:
          args: pack
        env:
          WORKING_DIR: client
      - name: Push to central
        uses: ballerina-platform/ballerina-action@394eb82cc07e020948fee8d1474143ae393147f4
        with:
          args: push
